# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: mdeglain <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2015/08/20 20:10:49 by mdeglain          #+#    #+#              #
#    Updated: 2015/08/20 20:14:40 by mdeglain         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = ft_cat

SRC = ./ft_cat.c

all: $(NAME)

$(NAME):
	gcc -Wall -Wextra -Wall $(SRC) -o $(NAME)

clean:
	/bin/rm -f $(NAME)
fclean: clean

re: fclean all
