# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: pmoulin <marvin@42.fr>                     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2015/07/23 14:38:32 by pmoulin           #+#    #+#              #
#    Updated: 2015/07/23 19:18:10 by pmoulin          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #


NAME = ft_display_file

SRC = display_file.c

all = $(NAME)

$(NAME):
	gcc -o $(NAME) $(SRC)

clean :
	/bin/rm -f display_file.o

fclean :
	/bin/rm -f $(NAME)

re : fcleam all
